### ISSUE TITLE
Please add a Gemfile and/or more information about what's required to run this.

### ISSUE THREAD

**Issue by travishaynes** [milodraco/CrypTools#1]
On Ubuntu 21.10, running a clean install of Ruby 3.1.0 with RVM and a fresh gemset, I get this error right out the gates after the splash screen draws:

    ct-en.rb:34:in `initialize': No such file or directory @ rb_sysopen - https://google.com/ (Errno::ENOENT)

Please add a Gemfile that has the version of Ruby that's required and whatever gems you need to have installed to make this work. The README right now just says, "you must have Ruby installed and updated," which isn't very useful.

**Comment by milodraco** [comment]
Just delete 33-39 lines and it should work.

**Comment by milodraco** [comment]
Just updated, now it should work.
